// Mocks generated by Mockito 5.4.6 from annotations
// in countries/test/features/initializer/initializer_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:countries/core/error/failure.dart' as _i6;
import 'package:countries/core/utils/logging_service.dart' as _i10;
import 'package:countries/domain/entities/country.dart' as _i7;
import 'package:countries/domain/repository/country_remote_repository.dart'
    as _i2;
import 'package:countries/domain/usecases/get_countries_usecase.dart' as _i3;
import 'package:countries/domain/usecases/get_local_countries_usecase.dart'
    as _i9;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountryRemoteRepository_0 extends _i1.SmartFake
    implements _i2.CountryRemoteRepository {
  _FakeCountryRemoteRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCountriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountriesUseCase extends _i1.Mock
    implements _i3.GetCountriesUseCase {
  MockGetCountriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryRemoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryRemoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryRemoteRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Country>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>>);
}

/// A class which mocks [GetLocalCountriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocalCountriesUseCase extends _i1.Mock
    implements _i9.GetLocalCountriesUseCase {
  MockGetLocalCountriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Country>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Country>>>);
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i10.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logInfo(String? message) => super.noSuchMethod(
    Invocation.method(#logInfo, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logWarning(String? message) => super.noSuchMethod(
    Invocation.method(#logWarning, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logError(String? message, {dynamic error, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [message],
          {#error: error, #stackTrace: stackTrace},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logDebug(String? message) => super.noSuchMethod(
    Invocation.method(#logDebug, [message]),
    returnValueForMissingStub: null,
  );
}
